### PR TITLE
Split draw cell action

### PR DESCRIPTION
**Pull request by xgbuils**
Hi @jvalen

I splitted the DRAW_CELL action in four actions related to active drawing tool. I think this change simplifies the logic.

Cheers!

### CODE REVIEW

**Comment by jvalen** [comment]
Hi @xgbuils!

I love the idea however I've just tested the development and the `color-picker` is not working as expected. The action `APPLY_COLOR_PICKER` is triggered and it is not handled properly.

Thank you! :+1:

**Comment by xgbuils** [comment]
Hi @jvalen, good catch!

Yes, I could handle APPLY_COLOR_PICKER for behaving like APPLY_PENCIL. But I think that dispatch   APPLY_COLOR_PICKER when the cell is clicked is little a weird. Because, when the user clicks the cell after closing the color picker, I think, it's not a color picker action, it's a pencil action. Then, I'm fixing it dispatching a new action SET_PENCIL_TOOL when the color picker is closed.

Sounds good?

**Comment by xgbuils** [comment]
Maybe instead of new SET_PENCIL_TOOL action when color picker is closed. I will dispatch an action `{type: SWITCH_TOOL, tool: PENCIL}`.

**Comment by jvalen** [comment]
Merged! Now it works perfectly.

Thank you!

**Pull request merged**
