### PR TITLE
modularize reducer: split helpers by state props

### PR DESCRIPTION
**Pull request by xgbuils**
Hi @jvalen 

The idea is starting to modularize reducer. The first step was checking what state properties are usually changed at the same time and grouping them. For example:

- `currenColor` and `paletteGridData` are converted to `{palette: {currentColor, grid}}`
- `frames`, `columns`, `rows` and `activeFrameIndex` are converted to `{frames: {list, columns, rows, activeIndex}}`
- `eraserOn`, `bucketOn`, `eyedropperOn`, `colorPikerOn` are wrapped into `drawingTools` prop.

Then, I created helpers like `palette.js`, `drawingTools.js`, `frames.js`, etc that create and transform this substates.

Finally, `reducer.js` consume these new helpers and `reducerHelpers.js` was removed.

This PR is too big. If you find some bug in this refactor, don't hesitate to contact me to fix it.

Thanks!

### CODE REVIEW

**Comment by jvalen** [comment]
Hi @xgbuils!

I like the new proposed reducer organization, I think it is a great improvement.
I'm on my way of reviewing the PR. I've found a couple of bugs (you can see the comments within the _file changed_ section) and a way to fix it.

Feel free to update the PR with the fixes, I'll try to review the whole thing asap.

Thank you very much!

**Comment by xgbuils** [comment]
Thanks jvalen 

I squashed the commit to not create noise in the commit history.

Cheers!

**Comment by xgbuils** [comment]
Hi @jvalen 

Creating tests for frames reducer in another branch I found another bug in `changeFrameInterval`. It's already fixed.

Cheers!

**Comment by jvalen** [comment]
I haven't found more issues so I've merged the PR.
Great job @xgbuils! thank you!

**Pull request merged**
